// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import {Component, OnInit} from '@angular/core';
import {Livro} from "../livro";
import {ControleEditoraService} from "../controle-editora.service";
import {ControleLivrosService} from "../controle-livros.service";
import {Editora} from "../editora";
import {Router} from "@angular/router";

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})

export class LivroDadosComponent implements OnInit{
  livro : Livro;
  autoresForm: string = '';
  public editoras: Array<Editora> = [];


  constructor(private router:Router,private servLivros:ControleLivrosService, private servEditora:ControleEditoraService) {
    this.livro = new  Livro();
  }


  ngOnInit() {
    this.editoras = this.servEditora.getEditoras();
    
  }

  incluir = async () => {
    this.livro.autores = this.autoresForm.split('\n');

    await this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  };
}

<main class='container'>
  <h1>Dados do Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>

    <div class="form-group mb-3">
      <label for="titulo">Titulo</label>
      <input type="text" class="form-control" id="titulo" name="titulo" [(ngModel)]="livro.titulo" required/>
    </div>

    <div class="form-group mb-3">
      <label for="resumo">Resumo</label>
      <textarea class="form-control" id="resumo" name="resumo" [(ngModel)]="livro.resumo" required></textarea>
    </div>

    <div class="form-group mb-3">
      <label for="editora">Editora*</label>
      <select class="form-control" id="editora" name="editora" [(ngModel)]="livro.codEditora" required>
        <option *ngFor="let editora of editoras;" value="{{editora.codEditora}}">{{editora.nome}}</option>
      </select>
    </div>

    <div class="form-group mb-3">
      <label for="autores">Autores (1 por linha)</label>
      <textarea class="form-control" id="autores" name="autores" [(ngModel)]="autoresForm" required></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Salvar Dados</button>
  </form>
</main>

// clientes/livros-next/pages/LivroDados.tsx
import type {NextPage} from "next";
import React, { useState } from "react";
import {router} from "next/client";
import styles from '@/styles/Home.module.css'
import controleLivros from "../classes/controle/ControleLivros";
import ControleEditora from "../classes/controle/ControleEditora";
import { useRouter } from "next/router";
import Livro from "@/classes/modelo/Livros";

const controleEditora = new ControleEditora()


const LivroDados: NextPage = () => {

    //metodo que pega o array de editora e modifica colocando value e text
    const opcoes = controleEditora.getEditoras().map((editora) => ({
        value: editora.codEditora,
        text: editora.nome
    }));
    //Defini as States inicial
    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState(opcoes[0].value);


    //redirecionar
    const navigate = (pagina: string) => router.push(pagina);

    const tratarCombo = (evento: any) => {
        const numerointeiro = parseInt(evento.target.value)
        setCodEditora(numerointeiro)
    }

    const incluir = (evento: any) => {
        evento.preventDefault();
        const livro = {
            _id: null,
            codEditora: codEditora,
            titulo: titulo,
            resumo: resumo,
            autores: autores.split("\n")
        };

        incluirLivro(livro);
    };

    const incluirLivro = async (livro: any) => {
        controleLivros.incluir(livro)
            .then(()=>{
                navigate("/LivroLista")
            })
    };

  return (
    <div className="container">
    <main>        
      <div className="container">
        <h1 className="text-center mt-4">Incluir Livro</h1>
        <form onSubmit={incluir} className=" mt-4">
          <div className="mb-3">
            <label htmlFor="titulo" className="form-label">
              Título
            </label>
            <input
              required
              type="text"
              className="form-control"
              id="titulo"
              value={titulo}
              onChange={(e) => setTitulo(e.target.value)}
            />
          </div>
          <div className="mb-3">
            <label htmlFor="resumo" className="form-label">
              Resumo
            </label>
            <textarea
              required
              className="form-control"
              id="resumo"
              value={resumo}
              onChange={(e) => setResumo(e.target.value)}
            ></textarea>
          </div>
          <div className="mb-3">
            <label htmlFor="autores" className="form-label">
              Autores (separados por linha)
            </label>
            <textarea
              required
              className="form-control"
              id="autores"
              value={autores}
              onChange={(e) => setAutores(e.target.value)}
            ></textarea>
          </div>
          <div className="mb-3">
            <label htmlFor="codEditora" className="form-label">
              Editora
            </label>
            <select
              required
              className="form-select"
              id="codEditora"
              value={codEditora}
              onChange={tratarCombo}
            >
              {opcoes.map((opcao) => (
                <option key={opcao.value} value={opcao.value}>
                  {opcao.text}
                </option>
              ))}
            </select>
          </div>
          <button type="submit" className="btn btn-primary">
            Incluir Livro
          </button>
        </form>
      </div>
    </main>
    </div>
  );
};

export default LivroDados;
